### ISSUE TITLE
parser : org.dcm4che3.io.DicomStreamException: Not a DICOM Stream 	at org.dcm4che3.io.DicomInputStream.guessTransferSyntax(DicomInputStream.java:850) 	at org.dcm4che3.io.DicomInputStream.<init>(DicomInputStream.java:145) 	at model.DCMParser.dcmFileParser(DCMParser.java:20) 	at test.JunitTestDicomVR.parseDCMFile(JunitTestDicomVR.java:10)

### ISSUE THREAD

**Issue by rajavishnu-k** [elninojk/dicomviewer#6]

**Comment by rajavishnu-k** [comment]
If we try to import any other non dcm extension file, we got this type of bug.
We caught this exception in UI and print "File could not be read"
